Repository zenorocha/clipboard.js, pull requests merged in 2021-01, with the labels that each got.

#719 Update dev dependencies.
  dist/clipboard.js
  dist/clipboard.min.js
  karma.conf.js
  package-lock.json
  package.json
Labels: dependencies

#720 Remove unnecessary code and add node version control
  .nvmrc
  dist/clipboard.js
  test/clipboard.js
Labels: improvement

#722 Adding basic Type definitions
  package-lock.json
  package.json
  src/clipboard.d.ts
  src/clipboard.test-d.ts
Labels: improvement

#723 Add GH templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/proposal.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/issue_template.md
Labels: documentation, no code
