Repository zenorocha/clipboard.js, pull requests merged in 2021-02, with the labels that each got.

#729 Chore upgrade husky
  .husky/.gitignore
  .husky/pre-commit
  package-lock.json
  package.json
Labels: dependencies

#730 Fix readme.md badge
  readme.md
Labels: documentation

#727 adding deploy action
  .github/workflows/publish.yml
Labels: improvement
